Mount google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Otherwise just change directory to 

In [ ]:
%cd /content/drive/MyDrive/pedestrainDetection

/content/drive/MyDrive/pedestrainDetection


Here is where we will use OpenCV to do some image analysis.  We will use haarcascades

In [ ]:
# Standard imports
from google.colab.patches import cv2_imshow
import cv2
import numpy as np
import os

#setup our haar cascade
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

#Setup the file director
DIR = "OBJTest_resized"
OutDIR = "peopleOut"

#loop through every iamage in the folder and do this stuff to i
imgFiles = [f for f in os.listdir(DIR) if f.endswith('.png')]
for imgName in imgFiles:
	
	fName = os.path.join(DIR, imgName)
	# Read image
	img = cv2.imread(fName)
	im = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

	
	people, weights = hog.detectMultiScale(im, winStride=(1,16))
	print(people)
	for (x,y,w,h) in people:
		img = cv2.rectangle(img, (x, y), (x+w, y+h),(255,0,0),5)#BGR, 2 is stroke weight

	outName = os.path.join(OutDIR, imgName)
	cv2.imwrite(outName,img)
	
cv2.waitKey(0)
cv2.destroyAllWindows()


[[674 502 182 363]
 [372 245 298 597]]
[[663 535 178 357]
 [367 261 301 602]]
[[826 265  71 141]
 [834  96  64 128]
 [831  61  82 163]
 [185 284 107 215]
 [357 190 377 754]]
[[732 553  82 164]
 [362 244 292 584]]
[[736 301  69 137]
 [363 270 315 631]]
[[802 225  90 180]
 [341 212 353 707]]
[[  8 425  97 194]
 [ 66 211 154 308]
 [337 251 333 665]]
[[735 473  73 146]
 [357 360 274 547]]
[[384 123  82 163]
 [312 264 336 672]]
[[421 520 142 283]
 [373 341 253 507]]
[[344 256 321 642]]
[[407  59  68 135]
 [381 346 300 600]]
[[294 385 154 308]
 [388 324 259 518]
 [630 240 320 640]
 [198 102 409 817]]
[[130 333 138 276]
 [794 235  67 134]
 [346 260 322 643]]
[[376 322 266 533]]
[[368 318 259 517]]
[[161 412 141 281]
 [310 222 359 717]]
[[352 320 294 587]]
[[154  43  87 174]
 [ 75  45  72 144]
 [276 104 447 894]]
[[154 126  79 157]
 [344 243 328 656]]
[[150  20  83 165]
 [ 66  19  78 156]
 [110  93 371 741]
 [285  94 431 862]]
[[844 159  88 176]
 [348 235 322 644]]
[[361 278 294 588]]
[[843   

In [ ]:
import numpy as np 
import cv2
from google.colab.patches import cv2_imshow
import os


DIR = 'OBJTest_resized'
OutDIR = 'peopleMask'
#loop through every iamage in the folder and do this stuff to i
imgFiles = [f for f in os.listdir(DIR) if f.endswith('.png')]
for fName in imgFiles:
  print(fName)
  
  image = cv2.imread(os.path.join(DIR,fName))
  mask = np.zeros(image.shape, dtype=np.uint8)
  gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  thresh = cv2.threshold(gray, 100, 200, cv2.THRESH_BINARY )[1]

  cnts = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
  cnts = cnts[0] if len(cnts) == 2 else cnts[1]
  threshold_area = 500
  for c in cnts:
      area = cv2.contourArea(c)
      if area > threshold_area:
          cv2.drawContours(mask, [c], -1, (255,255,255), -1)

  
  outName = os.path.join(OutDIR, fName)
  cv2.imwrite(outName,mask)
cv2.waitKey()

PWall_1.png
PWall_0.png
PWall_39.png
PWall_19.png
PWall_18.png
PWall_17.png
PWall_16.png
PWall_15.png
PWall_14.png
PWall_13.png
PWall_12.png
PWall_11.png
PWall_10.png
PWall_28.png
PWall_27.png
PWall_26.png
PWall_25.png
PWall_24.png
PWall_23.png
PWall_22.png
PWall_21.png
PWall_20.png
PWall_2.png
PWall_37.png
PWall_36.png
PWall_35.png
PWall_34.png
PWall_33.png
PWall_32.png
PWall_31.png
PWall_30.png
PWall_3.png
PWall_29.png
PWall_47.png
PWall_46.png
PWall_45.png
PWall_44.png
PWall_43.png
PWall_42.png
PWall_41.png
PWall_40.png
PWall_4.png
PWall_38.png
PWall_56.png
PWall_55.png
PWall_54.png
PWall_53.png
PWall_52.png
PWall_51.png
PWall_50.png
PWall_5.png
PWall_49.png
PWall_48.png
PWall_9.png
PWall_8.png
PWall_7.png
PWall_6.png


-1